services:

  - type: web
    name: tunnel-vault
    runtime: docker
    image:
      url: hashicorp/vault:1.17
    plan: free
    envVars:
      - key: VAULT_DEV_ROOT_TOKEN_ID
        sync: false
      - key: PORT
        value: 8200
    disk:
      name: vault-data
      mountPath: /vault/data
      sizeGB: 1

  - type: web
    name: tunnel-config-api
    runtime: docker
    dockerfilePath: ./Dockerfile.configapi
    dockerContext: .
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: VAULT_ADDR
        sync: false
      - key: VAULT_TOKEN
        sync: false
      - key: INTERNAL_CONFIG_API_KEY
        generateValue: true
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:10000

  - type: web
    name: tunnel-manager-worker
    runtime: docker
    dockerfilePath: ./Dockerfile.worker
    dockerContext: .
    plan: free
    envVars:
      - key: CONFIG_API_URL
        sync: false
      - key: INTERNAL_CONFIG_API_KEY
        sync: false
