// <auto-generated />
using System;
using Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20260223054851_AddAgentJobsTable")]
    partial class AddAgentJobsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.AgentJob", b =>
                {
                    b.Property<Guid>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<int>("CKy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiresAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("DATEADD(MINUTE, 2, GETUTCDATE())");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PickedUpAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResultJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValue("PENDING");

                    b.HasKey("JobId");

                    b.HasIndex("CKy", "Status", "CreatedAt")
                        .HasDatabaseName("IX_AgentJobs_CKy_Status");

                    b.ToTable("AgentJobs");
                });

            modelBuilder.Entity("Domain.Entities.CompanyProject", b =>
                {
                    b.Property<int>("CPKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CPKy"));

                    b.Property<int>("CKy")
                        .HasColumnType("int");

                    b.Property<string>("DbName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DbPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DbServer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DbUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrjKy")
                        .HasColumnType("int");

                    b.HasKey("CPKy");

                    b.ToTable("CompanyProject", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.UsrMas", b =>
                {
                    b.Property<int>("UsrKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsrKy"));

                    b.Property<short?>("AcsLvlKy")
                        .HasColumnType("smallint");

                    b.Property<int?>("BUKy")
                        .HasColumnType("int");

                    b.Property<short>("CKy")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("EntDtm")
                        .HasColumnType("smalldatetime");

                    b.Property<int?>("EntUsrKy")
                        .HasColumnType("int");

                    b.Property<string>("PID")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Pwd")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PwdTip")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<short>("SKy")
                        .HasColumnType("smallint");

                    b.Property<string>("Status")
                        .HasMaxLength(2)
                        .HasColumnType("char(2)");

                    b.Property<string>("UsrId")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("UsrNm")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<byte>("fGroup")
                        .HasColumnType("tinyint");

                    b.Property<bool?>("fInAct")
                        .HasColumnType("bit");

                    b.Property<bool>("fSysAccNm")
                        .HasColumnType("bit");

                    b.Property<byte?>("flApr")
                        .HasColumnType("tinyint");

                    b.HasKey("UsrKy");

                    b.ToTable("UsrMas", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
